### ISSUE TITLE
Compatibility with sonar 6.5

### ISSUE THREAD

**Issue by timart1n** [adnovum/sonar-build-breaker#27]
Hey guys.
I noticed that version 6.5 is not part of your compatibility matrix.
Have you tested it? Is it compatible or do you plan to add compatibility in a next release?

Cheers,
Tiago

**Comment by mjdetullio** [comment]
The compatibility table is non-exhaustive.  I no longer use SonarQube at $dayJob so I don't really keep up with the releases.  If I find some time to test it out, I'll update the table, but as long as the APIs the plugin uses are still available then the plugin should work without issue.  Feel free to try it out.

**Comment by SMUnlimited** [comment]
I have been using with sonar 6.7.1 lts with no noticeable issues

**Comment by Ishaks** [comment]
@SMUnlimited: Have you been using v2.1 or v2.2 with sonar 6.7.1?

**Comment by sandro-h** [comment]
Hey all, we now have a 2.3.0 release which supports SonarQube 7.3 - 7.9. There's no plan to fill in any gaps in older SonarQube versions, so I suggest you upgrade SonarQube to a recent version if you haven't already (the issue is quite old) :-)
