### ISSUE TITLE
compatibily matrix Jenkins and SonarQube v6.7.3 

### ISSUE THREAD

**Issue by bru2code** [adnovum/sonar-build-breaker#35]
HI, 

I can't see compatibility matrix of SonarQ and build breaker compaitibiliy matrix for SonarQube v6.7.3. Is build breaker v2.2 compatible with sonarQube v6.7.3. Do you know of a better way to break a Jenkins pipeline if this doesn't work?

Thanks, Raju

**Comment by sandro-h** [comment]
Hey @bru2code, late answer (we've since taken over maintainership of the plugin). In the meantime SonarQube has moved on to version 7.9 and we just released a compatible plugin version. If you haven't already, I suggest to move to a more up-to-date version of SonarQube.
