### ISSUE TITLE
Plugin is not compatible with Sonar 7.3

### ISSUE THREAD

**Issue by armsargis** [adnovum/sonar-build-breaker#38]
Plugin is not compatible with Sonae 7.3 because of removal of deprecated API as port of task:

(https://jira.sonarsource.com/browse/SONAR-10138)

**Comment by jothibasu-kamaraj** [comment]
When the new release going to happen with sonar 7.3 support

**Comment by oliyavan** [comment]
@armsargis this PR is merged or not?

**Comment by jothibasu-kamaraj** [comment]
@mstoecklmayr Any workaround in the meantime, Could you please suggest.

**Comment by sandro-h** [comment]
Hey all, we now have a [2.3.0 release](https://github.com/adnovum/sonar-build-breaker/releases/tag/2.3.0) which supports SonarQube 7.3 - 7.9.
