### ISSUE TITLE
[BuildBreaker] Link to the report is missing

### ISSUE THREAD

**Issue by artyom-krot** [adnovum/sonar-build-breaker#45]
When build breaker detects issues in the report it just shows numbers of errors in logs. 
example: 

> [error]ERROR: Open Issues: 2 > 0
> ERROR: [BUILD BREAKER] Project did not meet 1 conditions
> ERROR: Open Issues: 2 > 0

It needs additional efforts for developers to open SonarQube UI and try to find report for the specific project and specific branch.

It would be great to have link to the report in logs or even better to shows what specific errors we have in our code and what should be corrected.

Looks like that 2nd point is too complex, that is why I would suggest to throw just link to the report with errors in logs.
 
![image](https://user-images.githubusercontent.com/30717338/55325382-9d701100-548d-11e9-9eca-3bb51ea59f4b.png)

**Comment by sandro-h** [comment]
Hey @artyom-krot, when I run a sonar analysis, I get output like this before the build breaker kicks in:
```
[INFO] ANALYSIS SUCCESSFUL, you can browse http://localhost:9000/dashboard?id=org.sonarqubecommunity.buildbreaker%3Averification-failing
[INFO] Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
[INFO] More about the report processing at http://localhost:9000/api/ce/task?id=AW6Tm7Kl70ATlE1Pgld5
[INFO] Executing post-job 'Forbidden Configuration Breaker'
[INFO] Executing post-job 'Quality Gate Breaker'
[INFO] Waiting for report processing to complete...
[INFO] Quality gate status: ERROR
[ERROR] Vulnerabilities: 1 > 0
[ERROR] [BUILD BREAKER] Project did not meet 1 conditions
```

So it the normal Sonar analysis already displays a link to the project dashboard with `ANALYSIS SUCCESSFUL, you can browse ...`. Wouldn't that be sufficient? If you don't get such a link in your report, I'd be interested to know what version of SonarQube and the sonar scanner you're using.

**Comment by sandro-h** [comment]
I'm closing this as stale. Feel free to let us know if you do still have the issues (see my last comment).
