### ISSUE TITLE
Sonar-build-breaker plugin compatability on v7.9.1

### ISSUE THREAD

**Issue by Anusha-Madhavarapu** [adnovum/sonar-build-breaker#48]
Sonar build breaker plugin(2.2) is not compatible  with the sonarqube version 7.9.1 when can we expect release for the latest version ?

**Comment by sandro-h** [comment]
Hey @Anusha-Madhavarapu, since today we have a [2.3.0 release](https://github.com/adnovum/sonar-build-breaker/releases/tag/2.3.0) which supports SonarQube 7.3 - 7.9.
