### ISSUE TITLE
Sonar buildbreaker plugin breaking build even when quality gates does have issues reported

### ISSUE THREAD

**Issue by ksanjay7** [adnovum/sonar-build-breaker#55]
**Describe the bug**
Sonar build breaker plugin breaking build even when quality gates does have issues reported

**Context**
At the minimum, provide the SonarQube and plugin version: 

- SonarQube server version: ... 6.7.2
- sonar-build-breaker plugin version: ... 2.1
- Java version used for the Sonar analysis: ... Java 8
- Build context: manual execution / CI tool (TravisCI, CircleCI, ...)

**To Reproduce**

I have a project quality gate as -
Blocker Issues		is greater than	0
Bugs		is greater than	0
Condition Coverage		is less than	70
Critical Issues		is greater than	0
Line Coverage		is less than	80
Major Issues		is greater than	0
Unit Test Errors		is greater than	0
Unit Test Failures		is greater than	0
Vulnerabilities	 is greater than	0

And Results after a branch scan -

Issues
Type
Bug0 Vulnerability0 Code Smell15
Severity
Blocker0Minor15Critical0Info0Major0
Resolution
Unresolved15Fixed0False Positive0Won't fix0Removed0
Status
 Open15 Resolved0 Reopened0 Closed0 Confirmed0

**Expected behavior**
Quality gate should not break

**Logs**
SONAR --- Result:[[INFO] Executing post-job org.sonar.plugins.buildbreaker.ForbiddenConfigurationBreaker]
SONAR --- Result:[[INFO] Executing post-job org.sonar.plugins.buildbreaker.QualityGateBreaker]
SONAR --- Result:[[INFO] Waiting for report processing to complete...]
SONAR --- Result:[[INFO] Waiting for report processing to complete...]
SONAR --- Result:[[INFO] Quality gate status: ERROR]
SONAR --- Result:[[ERROR] Code Smells: 15 > 0]
SONAR --- Result:[[ERROR] [BUILD BREAKER] Project did not meet 1 conditions]

**Additional context**

**Comment by sandro-h** [comment]
Hi @ksanjay7,

Does the Sonar UI itself report the branch scan as having failed the quality gate? In theory the build breaker only reports the quality gate results that Sonar determined, so it could be a bug in Sonar itself, and not the plugin.

**Comment by sandro-h** [comment]
I'm closing this as stale. Feel free to let us know if you do still have the issues (see my last comment).
