### ISSUE TITLE
Add the plugin to the marketplace again

### ISSUE THREAD

**Issue by lg2de** [adnovum/sonar-build-breaker#56]
Because the plugin was not supported anymore by the SonarSource team, it was removed from the marketplace in 2016.
But you brought it back to life!!!
Why not try to add it again?

If you want to do so you may look on the commit removing it:
https://github.com/SonarSource/sonar-update-center-properties/commit/fd492f5cd4567bb8c4a14fc13c3e62fc457900ad

If you like I can create such change/PR for you.

**Comment by sandro-h** [comment]
Hi @lg2de,

It would certainly be convenient to have it in the marketplace again :) I can issue a PR after I go over the current marketplace prerequisites (I'm not sure if all the required metadata is present in the plugin, for example).

**Comment by sandro-h** [comment]
I've made a request to have the plugin added to the Marketplace again: https://community.sonarsource.com/t/requesting-inclusion-into-marketplace-for-sonar-build-breaker/20427

**Comment by PMasekind** [comment]
I have been doing a prove of concept at work and the development guys really love this plug-in. It would really be a win for me if this plug-in is added to the marketplace

**Comment by sandro-h** [comment]
Happy to announce that we've been added back into the marketplace! Older versions of the plugin will still have to be installed manually, but assuming you're using SonarQube 7.9+, you can now install the plugin version 2.3.1 (and any future versions) from the marketplace.

**Comment by PMasekind** [comment]
This is the best news ever. Thank you so much for the update. I can't wait
to collaborate with you guys.

Regards
Phemelo
