### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by nishaatr** [adnovum/sonar-build-breaker#62]
Is this plugin still supported and how often changes are made for compatibility with Sonar version?
I found this page https://community.sonarsource.com/t/build-breaker-plugin/10493 which says the plugin should not be used.
We have just installed this plugin on our new Sonar instance so prefer to know the future for the plugin.

**Comment by sandro-h** [comment]
Hi @nishaatr, yes the plugin is still supported (it was briefly unsupported until we took over maintainership). We're actively using it internally, so we plan to keep it compatible. Currently it's compatible up to the latest SonarQube version (8.4.2).
I'll update our compatibility table to reflect this, actually.
